// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNb2noF9NCHQzpuS6OCSdtDl3a8_oz-cA',
    appId: '1:1018176151615:web:acebeff44e79dc9410d88a',
    messagingSenderId: '1018176151615',
    projectId: 'shuttlezone-4e7bf',
    authDomain: 'shuttlezone-4e7bf.firebaseapp.com',
    storageBucket: 'shuttlezone-4e7bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHrag3sToGu9hjnjCbBZbaLr7J7T4eMgs',
    appId: '1:1018176151615:android:b23edee741efee3010d88a',
    messagingSenderId: '1018176151615',
    projectId: 'shuttlezone-4e7bf',
    storageBucket: 'shuttlezone-4e7bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNiy0Q0vwpjob4pL2pTtyvK1Dbi8_lqY',
    appId: '1:1018176151615:ios:30114e225d4eb81c10d88a',
    messagingSenderId: '1018176151615',
    projectId: 'shuttlezone-4e7bf',
    storageBucket: 'shuttlezone-4e7bf.firebasestorage.app',
    iosBundleId: 'com.example.shuttlezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNiy0Q0vwpjob4pL2pTtyvK1Dbi8_lqY',
    appId: '1:1018176151615:ios:30114e225d4eb81c10d88a',
    messagingSenderId: '1018176151615',
    projectId: 'shuttlezone-4e7bf',
    storageBucket: 'shuttlezone-4e7bf.firebasestorage.app',
    iosBundleId: 'com.example.shuttlezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNb2noF9NCHQzpuS6OCSdtDl3a8_oz-cA',
    appId: '1:1018176151615:web:b80b6a9f05399f3210d88a',
    messagingSenderId: '1018176151615',
    projectId: 'shuttlezone-4e7bf',
    authDomain: 'shuttlezone-4e7bf.firebaseapp.com',
    storageBucket: 'shuttlezone-4e7bf.firebasestorage.app',
  );

}